# Worktree Plus Configuration
version: '1.0'

# Default settings for worktrees
defaults:
  # Base directory for worktrees (relative to repository root)
  base_dir: ../worktrees/edu-aws-lights-out

# Hooks that run after creating a worktree
hooks:
  post_create:
    # Example: Copy gitignored files from MAIN worktree to new worktree
    # Note: 'from' is relative to main worktree, 'to' is relative to new worktree
    # - type: copy
    #   from: .env        # Copy actual .env file (gitignored)
    #   to: .env

    # Example: Run a command to show all worktrees
    # - type: command
    #   command: wtp list

    # More examples (commented out):

    # Copy AI context files (typically gitignored):
    # - type: copy
    #   from: .claude     # Claude AI context
    #   to: .claude
    # - type: copy
    #   from: .cursor/    # Cursor IDE settings
    #   to: .cursor/

    # Run setup commands:
    - type: command
      command: source ~/.nvm/nvm.sh && nvm use
    - type: command
      command: pnpm install
    - type: command
      command: pnpm exec husky init
    - type: command
      command: echo 'npx lint-staged' > .husky/pre-commit
